version: '3'

services:
  db:
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
  frontend:
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: backend/
    ports:
      - "8080:8080"
    depends_on:
      - db
  scripts:
    build: scripts/
    depends_on:
      - db